const quotes = [
    "First, we eat. Then, we do everything else.",
    "I’m not drooling, you are!",
    "Is it just me or does this meal look more scrumptious because I’m on a diet?",
    "I like people who love to eat. They’re the best kind of people in the world.",
    "Live, love, eat.",
    "Made with love.",
    "To live a full life, you have to fill your stomach first.",
    "Carbs might be my soulmate.",
    "All I want for Christmas is...food.",
    "Never eat more than you can lift.",
    "The most essential part of a well-balanced diet is—food!",
    "Hunger is a good cook.",
    "A little slice of heaven.",
    "Good food never fail in bringing people together.",
    "Eat right, exercise, die anyway.",
    "It’s essential for every party to have cake. If there’s no cake, then it’s only a meeting.",
    "9 out of 10 people love chocolate. And the 10th person is always lying.",
    "The chief ingredient in yummy food is love.",
    "There is no better reward for hard work than good food.",
    "They told me to follow my heart. Guess where it led me? To the fridge.",
    "Skinny people are easier to kidnap. Stay safe, eat cake.",
    "I’m soy into you.",
    "Life is about exploring the pasta-billities.",
    "Grill and chill!",
    "Good people, good food, good time.",
    "I’d hate to lie on my deathbed and think: “I could have eaten that!”",
    "One does not need silver cutlery to eat delectable food.",
    "Food shared is happiness multiplied.",
    "Eat, drink and live free. There’s no telling what might happen tomorrow.",
    "Oh, did you say exercise? I thought you said extra fries!",
    "Another one bites the crust.",
    "There’s nothing more romantic than a serene walk to the fridge.",
    "Life is infinitely delicious.",
    "Breakfast food can cure all sadness away.",
    "What... diet?",
    "Dine well and you’ll be able to think well, sleep well, and live well.",
    "Cupcakes are muffins that believed in miracles.",
    "For some reason, food tastes better when it’s somebody‘s treat.",
    "Everything you see, I owe to spaghetti.",
    "Dinner is one of life’s greatest pleasures.",
    "I’m obsessed with food.",
    "How do I like my eggs? In cake, of course!",
    "Chocolate makes everything better.",
    "I'm so eggcited to eat!",
    "I just want someone to utter these three magic words to me: “I brought food.”",
    "Good food, good mood.",
    "This is a festival of flavors.",
    "There is no “we” in fries. Remember that!",
    "There’s nothing more romantic than Italian food.",
    "I’m on a 30-day diet. So far, I’ve lost 15 days.",
    "Where there is good food, there is happiness.",
    "Let’s eat some diet food while we wait for the steak to cook.",
    "In the mood for noods.",
    "Eat today, live another day.",
    "I’m never giving up on chocolate! I’m not a quitter!",
    "I am on a seafood diet. I see food, I eat it.",
    "A day is best started on a full stomach."
]

export default () => {return quotes[Math.floor(Math.random() * quotes.length)];}