export const test_products = [
    {
        "_id": "0.4526504092385989",
        "title": "Chia Seeds",
        "image": null,
        "category": "Dryfruit's Seeds",
        "price": 89,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.20714198057199096",
        "title": "Alsi (flex) Seeds",
        "image": null,
        "category": "Dryfruit's Seeds",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.020137193011940835",
        "title": "Pumkin Seeds",
        "image": null,
        "category": "Dryfruit's Seeds",
        "price": 160,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.653234573604085",
        "title": "Sunflower Seeds",
        "image": null,
        "category": "Dryfruit's Seeds",
        "price": 59,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.746708563850595",
        "title": "Quinoa",
        "image": null,
        "category": "Dryfruit's Seeds",
        "price": 395,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7112387209074429",
        "title": "6 Seeds Mix",
        "image": null,
        "category": "Dryfruit's Seeds",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7875788864044696",
        "title": "Maghai Paan",
        "image": null,
        "category": "Mukhwas Paan",
        "price": 140,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9397753487503275",
        "title": "Dryfruit Gulkand",
        "image": null,
        "category": "Mukhwas Paan",
        "price": 199,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.45395804693397557",
        "title": "Culcutta Jintan Paan",
        "image": null,
        "category": "Mukhwas Paan",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4246699404642934",
        "title": "Golden Paan",
        "image": null,
        "category": "Mukhwas Paan",
        "price": 110,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5946628809006871",
        "title": "All Mix Assorted Chikki Box (800gm)",
        "image": null,
        "category": "Combo Pack (With Exclusive Gift Box)",
        "price": 499,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3086663507524925",
        "title": "Ratlami Sev / Long Sev / Gujrati Papdi / Special Cookies / Dryfruit Chikki / Suji Toast",
        "image": null,
        "category": "Combo Pack (With Exclusive Gift Box)",
        "price": 499,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.30840386337507353",
        "title": "Ratlami Sev / Golden Mixture/salted Chips (box Pack) / Choclate Bytes/ Special Khari (box Pack)",
        "image": null,
        "category": "Combo Pack (With Exclusive Gift Box)",
        "price": 370,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9916414204957854",
        "title": "Gudh Rewdi 250gms",
        "image": null,
        "category": "Gajak Rewdi Items",
        "price": 55,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.21702674603715688",
        "title": "Special Rewdi 250gms",
        "image": null,
        "category": "Gajak Rewdi Items",
        "price": 55,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.20540623546532888",
        "title": "Tomato Aloo Bhujiya",
        "image": null,
        "category": "Namkeen Sev",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8549476101380122",
        "title": "Instant Poha Sev 200gm",
        "image": null,
        "category": "Namkeen Sev",
        "price": 50,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3124976678663781",
        "title": "Fiki Sev 400gm Box Pack",
        "image": null,
        "category": "Namkeen Sev",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3755477591053866",
        "title": "Kadak Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 65,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6335702441412459",
        "title": "Sabzi Ki Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 65,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.42134140198565506",
        "title": "Doodh Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8464842471049179",
        "title": "Achari Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5532351137744178",
        "title": "Fiki Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.40665347959076803",
        "title": "Barik Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 65,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.1556498158599765",
        "title": "Hing Sev 400gm Box Pack",
        "image": null,
        "category": "Namkeen Sev",
        "price": 140,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5280972795876224",
        "title": "Hing Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 70,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.22385652407721346",
        "title": "Ratlami Sev 400gm Box Pack",
        "image": null,
        "category": "Namkeen Sev",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5718074587587944",
        "title": "Ratlami Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.59485611567851",
        "title": "Ujjaini Sev 400gm Box Pack",
        "image": null,
        "category": "Namkeen Sev",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9263205754272497",
        "title": "Ujjaini Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.43109909646119826",
        "title": "Long Sev 400gm Box Pack",
        "image": null,
        "category": "Namkeen Sev",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.03539487404235575",
        "title": "Long Sev",
        "image": null,
        "category": "Namkeen Sev",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7661906633766817",
        "title": "Roasted Chana 500gms",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 159,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.22138316260801771",
        "title": "Roasted Chana (250gms)",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 79,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6129394939551427",
        "title": "Hara Batla Small Pack",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 39,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2116781600844857",
        "title": "Roasted Multigran (150grms)",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 65,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3132634998936914",
        "title": "Roasted Soyabean (100 grms)",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 45,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.46486908196871046",
        "title": "Roasted Dal Jor (100 grms)",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 45,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5701644219320586",
        "title": "Roasted Moth (100 grms)",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 45,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.22519306455981403",
        "title": "Roasted 9in1 (150 grms)",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 55,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9966583532058306",
        "title": "Roasted Moong Masala",
        "image": null,
        "category": "Namkeen Roasted Items",
        "price": 45,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.36272323889898117",
        "title": "Mini Samosa",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 80,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3688175303106044",
        "title": "Cheese Ball 80gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 55,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.14561573933723726",
        "title": "Gehu Frymes Masala",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 25,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.33597398902034836",
        "title": "Gehu Frymes Plain",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 25,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.33756019126767234",
        "title": "Potato Frymes Salted",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 48,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8345295064095799",
        "title": "Potato Frymes Masala",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 48,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9147605610784234",
        "title": "Sandwich Bhakharwadi",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4295849296224479",
        "title": "Namak Pare 200gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 56,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6640763147607184",
        "title": "Methi Mathri",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 69,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9081931442091412",
        "title": "Salted Chana",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 89,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.29137586414738215",
        "title": "Hing Dry Chana",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 79,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.42512505004724355",
        "title": "Hing Masala Chana 200gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 69,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.24415286048566487",
        "title": "Milk Chana",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 79,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2969191442887761",
        "title": "Chana Tasty 200gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 72,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.19817073599901336",
        "title": "Chana Jor 200gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 69,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.12468208455800256",
        "title": "Salted Dana 200gm5",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 54,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.37678572195837057",
        "title": "Kali Mirch Dala 250gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 79,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6482500863803934",
        "title": "Hing Tasty 250gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 89,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8777575208880396",
        "title": "Chakli 200gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 48,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6220721497233973",
        "title": "Pani Puri Chakli 180gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 69,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.0835303359383659",
        "title": "Lauhsan Stick 200gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 89,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7071485373989295",
        "title": "Joy Stick",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 89,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5244570280956058",
        "title": "Soya Sticks",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 79,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6317569432860788",
        "title": "Chakli Stick 180gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 52,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.18170728919153867",
        "title": "Plain Mathri",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.02504470382387447",
        "title": "Namkeen Kaju 200gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.36522803479586485",
        "title": "Sugar Coated Pare 200gm",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.1359129102970278",
        "title": "Moong Butter Stick",
        "image": null,
        "category": "Namkeen Snacks Items",
        "price": 89,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.593417510279177",
        "title": "Moong Khakhra",
        "image": null,
        "category": "Namkeen Khakhra",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5033584432563238",
        "title": "Cheese Khakhra",
        "image": null,
        "category": "Namkeen Khakhra",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4512735130420732",
        "title": "Chatpata Khakhra",
        "image": null,
        "category": "Namkeen Khakhra",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.21488342298402463",
        "title": "Punjabi Khakhra",
        "image": null,
        "category": "Namkeen Khakhra",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5687837394735348",
        "title": "Masala Khakhra",
        "image": null,
        "category": "Namkeen Khakhra",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.1429143486985025",
        "title": "Jeera Khakhra",
        "image": null,
        "category": "Namkeen Khakhra",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.23385882919264644",
        "title": "Laushan Khakhra",
        "image": null,
        "category": "Namkeen Khakhra",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8938318816997873",
        "title": "Panipuri Khakhra",
        "image": null,
        "category": "Namkeen Khakhra",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3613380543084215",
        "title": "Mogu Mogu Drink",
        "image": null,
        "category": "Imported Drinks",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4798470944252041",
        "title": "Starbucks Vanilla (ready To Drink)",
        "image": null,
        "category": "Imported Drinks",
        "price": 370,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6270105378357157",
        "title": "Starbucks (caramel) Ready To Drink",
        "image": null,
        "category": "Imported Drinks",
        "price": 370,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8008217059495609",
        "title": "Starbucks Coffee (ready To Drink)",
        "image": null,
        "category": "Imported Drinks",
        "price": 370,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6481053646680497",
        "title": "Starbucks Coffee (mocha) Ready To Drink",
        "image": null,
        "category": "Imported Drinks",
        "price": 370,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8985327401234322",
        "title": "Red Bull Thailand Edition",
        "image": null,
        "category": "Imported Drinks",
        "price": 199,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6355061431258753",
        "title": "Red Bull",
        "image": null,
        "category": "Imported Drinks",
        "price": 220,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9922897391269728",
        "title": "Hubba Bubba Gum (Tangy Tropical)",
        "image": null,
        "category": "Imported Chocolates",
        "price": 249,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4214608026516008",
        "title": "Hubba Bubba Gum (Blue Raspberry)",
        "image": null,
        "category": "Imported Chocolates",
        "price": 249,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.26261332782437297",
        "title": "Hubba Bubba Gum (Cola)",
        "image": null,
        "category": "Imported Chocolates",
        "price": 249,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2864166373942848",
        "title": "Hubba Bubba Gum (Fruit)",
        "image": null,
        "category": "Imported Chocolates",
        "price": 249,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.14952581317350266",
        "title": "Hubba Bubba Gum (Strawberry)",
        "image": null,
        "category": "Imported Chocolates",
        "price": 249,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3840013185286515",
        "title": "Nutella Chocolate Bar (B_ Ready)",
        "image": null,
        "category": "Imported Chocolates",
        "price": 150,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9210629140271817",
        "title": "Imported Dairymilk (hazelnut) Thailand Edition",
        "image": null,
        "category": "Imported Chocolates",
        "price": 280,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.37451730071966316",
        "title": "Imported Dairymilk (Black Forest) Thailand Edition",
        "image": null,
        "category": "Imported Chocolates",
        "price": 280,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6063889683168715",
        "title": "Sugar Free Chocolate",
        "image": null,
        "category": "Imported Chocolates",
        "price": 349,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6887047625212179",
        "title": "Ferraro Rocher (Box Pack)",
        "image": null,
        "category": "Imported Chocolates",
        "price": 599,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.11700921898607708",
        "title": "Tilii Ladoo 400gm",
        "image": null,
        "category": "Chikki Items",
        "price": 180,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3750198444235542",
        "title": "Peanut Laddoo (400gms)",
        "image": null,
        "category": "Chikki Items",
        "price": 219,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.154103227574221",
        "title": "Tilli Ladoo (200gms)",
        "image": null,
        "category": "Chikki Items",
        "price": 100,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9794324621050452",
        "title": "Anjeer Chikki (500Gms)",
        "image": null,
        "category": "Chikki Items",
        "price": 699,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2752587809714372",
        "title": "Peanut Chikki (500Gms)",
        "image": null,
        "category": "Chikki Items",
        "price": 199,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.18355950457540404",
        "title": "Rajgira Dana Chikki (500Gms)",
        "image": null,
        "category": "Chikki Items",
        "price": 210,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.21064198199617923",
        "title": "Dryfruit Chikki (500Gms)",
        "image": null,
        "category": "Chikki Items",
        "price": 519,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6052173827596016",
        "title": "Rajgira Ladoo [16pc]",
        "image": null,
        "category": "Chikki Items",
        "price": 55,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4066006765204413",
        "title": "Peanut Chikki (250 gms)",
        "image": null,
        "category": "Chikki Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3865589214466466",
        "title": "Parmal Laddoo (16pcs.)",
        "image": null,
        "category": "Chikki Items",
        "price": 55,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5511956585351689",
        "title": "Anjeer Chikki (250 gms) (sugar Free)",
        "image": null,
        "category": "Chikki Items",
        "price": 349,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9193511460600108",
        "title": "Bold Badam (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 349,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.43212628964145805",
        "title": "Bold Kaju (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 349,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5090340831966371",
        "title": "Super Badam (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 299,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5425549261449197",
        "title": "Super Kaju (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 349,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5461295425626228",
        "title": "Fried Makhana (100gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 199,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6566726150905058",
        "title": "Kharak (500Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 230,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8074886382743697",
        "title": "Super Kaju (500Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 550,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9914708476598427",
        "title": "Bold Kaju (500Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 590,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.33628637647336823",
        "title": "Super Badam (500Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 470,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.17199669239695992",
        "title": "Kishmish 250gm",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 175,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.30734710764734463",
        "title": "Bold Anjeer (500gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 799,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7369378512759697",
        "title": "Pista Roasted(250 Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 530,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8614049927845087",
        "title": "Akhrot Giri (250 Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 415,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9449816028378283",
        "title": "Akhrot Shel (500gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 460,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.15105392861970535",
        "title": "Roasted Kaju (250 Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 399,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.21047924162904674",
        "title": "Roasted Badam (200 Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 299,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6600660008426567",
        "title": "California (Prunes)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 340,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.551881285701517",
        "title": "Seeds Nd Nuts",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 780,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8373348881968768",
        "title": "Blue Berries",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 792,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3908292242433836",
        "title": "Seeds Nd Berries",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 798,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9915489316026355",
        "title": "Nuts Nd Berries",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 590,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.41321450426335704",
        "title": "Fitmix",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 648,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.846081109111987",
        "title": "Jardalu (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 199,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5984041125347408",
        "title": "Black Kishmish",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 180,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9689791769310203",
        "title": "Monnaca Kishmish",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 265,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.01536115218277967",
        "title": "Afgaan Kishmish",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 239,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7286802309371938",
        "title": "Pista Without Shell (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 550,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5921084486697687",
        "title": "Bold Makhana (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 339,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8183980610329108",
        "title": "Seedless Dates (500Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 390,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9047935576014652",
        "title": "Bold Dates (500Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 336,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.05914571112399036",
        "title": "Bold Badam (500Gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 550,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3013201011831208",
        "title": "Kimia Dates",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 280,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.901733505000221",
        "title": "Anjeer (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 499,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3428895887268254",
        "title": "Turkey Appricots",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 225,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4818347849087925",
        "title": "Khus Khus (250 gms)",
        "image": null,
        "category": "Primium Dryfruit Range",
        "price": 425,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2488800844918606",
        "title": "Rice Flakes Chiwda",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 79,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2973265759729533",
        "title": "Gehu Chiwda",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 89,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9535689823487967",
        "title": "Kalash Hit Mixture",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.20324198549012495",
        "title": "Golden Mixture (400gms)( Box Pack)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.009416211334002278",
        "title": "Khatta Mettha Mixture (400gms) Box Pack",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.13991918168574147",
        "title": "Khatta Meetha Mixture",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.26748822128092076",
        "title": "Corn Flakes Mixture (charkha)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2906706846502224",
        "title": "Corn Mixture (Mitha)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6895583144102948",
        "title": "Wheat Puff 200gm",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 65,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5288357437832122",
        "title": "Plain Parmal (200gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 30,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.975748099093403",
        "title": "Hing Dal Special (250 gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 84,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7549887638770091",
        "title": "Rajgira Faryali",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5259248574704475",
        "title": "Meetha Faryali Mixture",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 81,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8548066261409779",
        "title": "Charkha Faryali Mixture",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6865197034489935",
        "title": "Sabudana Faryali",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 79,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6452361936545503",
        "title": "Shahi Dal Moth (200gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8924288662021885",
        "title": "Madrasi Mixture (500Gms) Box Pack",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5702642016332448",
        "title": "Madrasi Mixture (250 gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.44158935801537935",
        "title": "Lajawab Mixtue (500Gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5020511734346752",
        "title": "Lajawab Mixture (250 gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3992109841424434",
        "title": "Cornflakes Charkha Mixture (250 gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5580754682520777",
        "title": "Hing Mixture (250 gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 78,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5588151507229978",
        "title": "Hing Mixture (400gms) (Box Pack)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 144,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6646270598093139",
        "title": "Punjabi Mixture (250 gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 60,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4041250099990442",
        "title": "Punjabi Mixture (500 Gm) Box Pack",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.31354972690058214",
        "title": "All In One (250 gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 75,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2774376944742908",
        "title": "Laushan Parmal (200gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 48,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.05668114428389637",
        "title": "Aaloo Lacha Lal (200gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 62,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.41147302769707594",
        "title": "Sindhi Papad (250 gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.21660411775896826",
        "title": "Sindhi Papad (500Gms)",
        "image": null,
        "category": "Namkeen Mixture Items",
        "price": 199,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4772484663727883",
        "title": "Mango Bytes",
        "image": null,
        "category": "Pop Up Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7627290473658167",
        "title": "Vanilla Bytes",
        "image": null,
        "category": "Pop Up Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7807123720135904",
        "title": "Chocolates Bytes",
        "image": null,
        "category": "Pop Up Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9362627951464204",
        "title": "Strawberry Bytes",
        "image": null,
        "category": "Pop Up Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.48987724500358865",
        "title": "Pianapple Bytes",
        "image": null,
        "category": "Pop Up Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.04653058575512503",
        "title": "Vip Dry Frut Mixture",
        "image": null,
        "category": "Dry Fruit Mixture",
        "price": 129,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.028500540325486323",
        "title": "Badam Lacha 200 Gms Box Pck",
        "image": null,
        "category": "Dry Fruit Mixture",
        "price": 149,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2552639800366866",
        "title": "Makhana Dry Fruit Mixture 200 Gms",
        "image": null,
        "category": "Dry Fruit Mixture",
        "price": 125,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8755918899859433",
        "title": "Dry Fruit Cornflakes Mixture (200gms)",
        "image": null,
        "category": "Dry Fruit Mixture",
        "price": 90,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7344009960777368",
        "title": "Ginger Pachak",
        "image": null,
        "category": "Pachak Items",
        "price": 72,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5455309634422129",
        "title": "Pipal Pachak",
        "image": null,
        "category": "Pachak Items",
        "price": 47,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5046545672154923",
        "title": "Ajwain Namkeen",
        "image": null,
        "category": "Pachak Items",
        "price": 59,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9117480414592255",
        "title": "Hing Peda",
        "image": null,
        "category": "Pachak Items",
        "price": 72,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7393182511209617",
        "title": "Pudina Pachak Goli",
        "image": null,
        "category": "Pachak Items",
        "price": 65,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6186908054909631",
        "title": "Hing Pachak Goli",
        "image": null,
        "category": "Pachak Items",
        "price": 71,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.44173995114824316",
        "title": "Harade Pachak",
        "image": null,
        "category": "Pachak Items",
        "price": 59,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5970739573187912",
        "title": "Anar Gulkand Chips",
        "image": null,
        "category": "Pachak Items",
        "price": 62,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5864361361613183",
        "title": "Kharag Pachak",
        "image": null,
        "category": "Pachak Items",
        "price": 86,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.762183741177154",
        "title": "Jeera Aamchur",
        "image": null,
        "category": "Pachak Items",
        "price": 54,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.21681042302051567",
        "title": "Mix Fruit Balls",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 72,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3785098676929646",
        "title": "Mango Balls Goli",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 59,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3121583700860877",
        "title": "Hing Goli",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 66,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.021545666263263374",
        "title": "Jeera Goli",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 65,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.017291987753791926",
        "title": "Anardana Goli",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 59,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4598417034059744",
        "title": "Hazma Hazam Goli",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 65,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.06914439043976794",
        "title": "Jaamun Goli 150",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 66,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6427202800540222",
        "title": "Munakka Pachak 150Gm",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 96,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.994459171361209",
        "title": "Ber Namkeen 150Gm",
        "image": null,
        "category": "Mukhwaas Goli",
        "price": 48,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.20136752822893522",
        "title": "Shahi Mix",
        "image": null,
        "category": "Mukhwaas Sonf",
        "price": 54,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.23091521471245613",
        "title": "Bambaiya Sonf",
        "image": null,
        "category": "Mukhwaas Sonf",
        "price": 58,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5884867952164867",
        "title": "Rajsthani Kaththa Sonf",
        "image": null,
        "category": "Mukhwaas Sonf",
        "price": 66,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9946221996021959",
        "title": "Shahi Sonf",
        "image": null,
        "category": "Mukhwaas Sonf",
        "price": 67,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.3582015811761623",
        "title": "Roasted Sonf With Mulethi & Dal",
        "image": null,
        "category": "Mukhwaas Sonf",
        "price": 72,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.09872525905797136",
        "title": "Special Mint Sonf",
        "image": null,
        "category": "Mukhwaas Sonf",
        "price": 66,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8039886023358301",
        "title": "Thandai Mix Sonf",
        "image": null,
        "category": "Mukhwaas Sonf",
        "price": 66,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.641759879099174",
        "title": "Kaju Awla",
        "image": null,
        "category": "Mukhwaas Awla Items",
        "price": 130,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5964560885054879",
        "title": "Pan Awla",
        "image": null,
        "category": "Mukhwaas Awla Items",
        "price": 130,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6542482666500782",
        "title": "Awla Pachak",
        "image": null,
        "category": "Mukhwaas Awla Items",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7159279291275864",
        "title": "Anar Awla",
        "image": null,
        "category": "Mukhwaas Awla Items",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.47940340681316607",
        "title": "Namkeen Awla Crush",
        "image": null,
        "category": "Mukhwaas Awla Items",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7918956729437372",
        "title": "Awla Special",
        "image": null,
        "category": "Mukhwaas Awla Items",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.47977824624921706",
        "title": "Kesar Supari",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 75,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.01931256211965149",
        "title": "Fruits Silver Supari",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 239,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6628130205350415",
        "title": "Khus Silver Supari",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 359,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5206948757738579",
        "title": "Chikni Barik Supari",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 74,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.02049514006415165",
        "title": "Khajur Supari",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 67,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9655335101090875",
        "title": "Bon Supari",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 84,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.04458122509392426",
        "title": "Kesar Lacha Supari",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 86,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4992134027981576",
        "title": "Fruit Silver Supari (100gms)",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 222,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9853827688166825",
        "title": "Pakiza Soft Supari (100gms)",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 119,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4485570342818981",
        "title": "Bon Chips Supari (100gms)",
        "image": null,
        "category": "Mukhwaaas Supari Items",
        "price": 126,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.14436457481484422",
        "title": "Chocolate Gems Cookies",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 149,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.12585434188986977",
        "title": "Suji Milk Toast (500Gms)",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 150,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.09955398283072348",
        "title": "Aata Toast Box Pack",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 80,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.12540159853878274",
        "title": "Veg Cake Rusk",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 170,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9661760349511634",
        "title": "Coconut Butter Cookies",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 199,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9829054517481103",
        "title": "Naan Khatai Cookies (Butter)",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 199,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5434921428448765",
        "title": "Honey Oats Cookies",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 249,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.008571709363292435",
        "title": "Aata Cookies (Butter)",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 249,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.05922343866184654",
        "title": "Jam Roll Cookies",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 130,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.09661834423960136",
        "title": "Butter Namkeen Cookies",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 120,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5275841186442767",
        "title": "Special Khari (250 gms) (Box Pack)",
        "image": null,
        "category": "Bakery Products (Pure Veg)",
        "price": 90,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.2513303314916019",
        "title": "Mix Fruit Pudding Cup",
        "image": null,
        "category": "Cakes",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9386508286168734",
        "title": "Hershey's Cake",
        "image": null,
        "category": "Cakes",
        "price": 410,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4455698293064607",
        "title": "Mix Fruit Special Cake",
        "image": null,
        "category": "Cakes",
        "price": 399,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.026698771114260667",
        "title": "Choco Chips Special Cake",
        "image": null,
        "category": "Cakes",
        "price": 399,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.6273859153664728",
        "title": "Choclate Cake",
        "image": null,
        "category": "Cakes",
        "price": 340,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.9090907594249453",
        "title": "Rabdi Cake (Prior Order)",
        "image": null,
        "category": "Cakes",
        "price": 450,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.12410236995778767",
        "title": "Strawberry Cake",
        "image": null,
        "category": "Cakes",
        "price": 299,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.38495400258236856",
        "title": "Vanilla Cake",
        "image": null,
        "category": "Cakes",
        "price": 290,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.17021238874374256",
        "title": "Red Walwet Cake",
        "image": null,
        "category": "Cakes",
        "price": 330,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.5841786374008665",
        "title": "White Forest Cake",
        "image": null,
        "category": "Cakes",
        "price": 320,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.776828805049905",
        "title": "Choco Pudding Cup",
        "image": null,
        "category": "Cakes",
        "price": 99,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7012227025712532",
        "title": "Butter Scotch Cake",
        "image": null,
        "category": "Cakes",
        "price": 320,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.26307418353319556",
        "title": "Black Forest Cake",
        "image": null,
        "category": "Cakes",
        "price": 340,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.8659577232356344",
        "title": "Kalash Special Gajak (250 gms)",
        "image": null,
        "category": "Gajak",
        "price": 95,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.042302766229077804",
        "title": "Shahi Khasta Gajak Gm250",
        "image": null,
        "category": "Gajak",
        "price": 50,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7228584965046383",
        "title": "Shahi Khasta Gajak (400gms)",
        "image": null,
        "category": "Gajak",
        "price": 100,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.15869969981478615",
        "title": "Kalash Special Gajak (350gm)",
        "image": null,
        "category": "Gajak",
        "price": 130,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.4489313797350547",
        "title": "Till Patti Gajak 400 Gms",
        "image": null,
        "category": "Gajak",
        "price": 205,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    },
    {
        "_id": "0.7042436949039108",
        "title": "Sing Dana Gajak (400gms)",
        "image": null,
        "category": "Gajak",
        "price": 144,
        "full_size": false,
        "show_priority": 0,
        "in_stock": false,
        "keywords": "",
        "veg": true
    }
]

export const test_categories = [
    {
        "_id": "0.2687631285967318",
        "title": "Dryfruit's Seeds",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.3834950519837421",
        "title": "Mukhwas Paan",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.2837353339677119",
        "title": "Combo Pack (With Exclusive Gift Box)",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.860331812426071",
        "title": "Gajak Rewdi Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.6601837356149889",
        "title": "Namkeen Sev",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.609517279808659",
        "title": "Namkeen Roasted Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.07172293608829428",
        "title": "Namkeen Snacks Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.5044713047152899",
        "title": "Namkeen Khakhra",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.7021856489778491",
        "title": "Imported Drinks",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.3596580021559269",
        "title": "Imported Chocolates",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.4566418594417867",
        "title": "Chikki Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.7621381938436813",
        "title": "Primium Dryfruit Range",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.21376654357906788",
        "title": "Namkeen Mixture Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.7065632307418288",
        "title": "Pop Up Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.38704863962532055",
        "title": "Dry Fruit Mixture",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.9544784937799226",
        "title": "Pachak Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.1900261640747073",
        "title": "Mukhwaas Goli",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.32752968420450934",
        "title": "Mukhwaas Sonf",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.08250093654940249",
        "title": "Mukhwaas Awla Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.4127825560341436",
        "title": "Mukhwaaas Supari Items",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.665304975335868",
        "title": "Bakery Products (Pure Veg)",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.3423111167546784",
        "title": "Cakes",
        "image": null,
        "priority": 0
    },
    {
        "_id": "0.949417578527445",
        "title": "Gajak",
        "image": null,
        "priority": 0
    }
]

export const test_content_values = [
    {
        "_id": "0.4526504092385989",
        "min_order_value": 1500,
        "delivery_charge": 50,
    },
]